env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh
  - rustc -v
script:
  - cargo build --verbose
  - cargo doc --no-deps --verbose
  - mv target/doc doc
notifications:
  email:
    on_success: change
    on_failure: change
