env:
  global:
    - secure: gCLMuRsPBINA459kgJOZOph9pqEUzu/oH7e5DhCbJTLV0n4kK6BN1wpqQlVDIe8640imEzwlPZvqYSmf4d9Rww78YvP7AWTxM8WajkN6vW/oJXMShhSLjw5u9qiIvTIvRkh5HcfsAfNszs2vKcdGMeG6VQfs3elNB2UqTGj3oyA=
    - LD_LIBRARY_PATH: /usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh
  - rustc -v
script:
  - cargo build --verbose
  - cargo doc --no-deps --verbose
  - mv target/doc doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
notifications:
  email:
    on_success: change
    on_failure: change
os:
  - linux
  - osx
